# Generated by Django 5.1.4 on 2024-12-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='token_created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
    ]
